version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - copyloopvar
    - depguard
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funcorder
    - gochecknoglobals
    - intrange
    - ireturn
    - lll
    - mnd
    - nlreturn
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - paralleltest
    - perfsprint
    - staticcheck
    - tagalign
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 20
    misspell:
      locale: US
    revive:
      rules:
        - name: var-naming
          disabled: true
    staticcheck:
      checks:
        - -ST1003
        - all
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - err113
          - funlen
          - goconst
          - mnd
          - noctx
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 50
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
